version: '3.7'
services:
  application:
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=springbootblog
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
      - SMTP_HOST=
      - SMTP_USERNAME=
      - SMTP_PASSWORD=
      - SMTP_PORT=
      - SECURITY_REMEMBER_ME_KEY=example-key
    networks:
      - spring-boot-blog
    ports:
      - '8080:8080'
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=springbootblog
    networks:
      - spring-boot-blog
    volumes:
      - 'mysql:/var/lib/mysql'
networks:
  spring-boot-blog:
    driver: bridge
volumes:
  mysql:
    driver: local
