spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:springbootblog}?autoReconnect=true
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:liquibase-migrations.xml
  h2:
    console:
      enabled: false
  messages:
    fallback-to-system-locale: false
  mail:
    host: ${SMTP_HOST}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    port: ${SMTP_PORT}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    web:
      pageable:
        default-page-size: 10
  web:
    resources:
      static-locations:
        - "file:src/main/resources/static/"
        - "classpath:/static/"
security:
  remember-me:
    key: ${SECURITY_REMEMBER_ME_KEY}
    token-validity-seconds: 604800
