spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:springbootblog}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:liquibase-migrations.xml
  h2:
    console:
      enabled: false
  messages:
    fallback-to-system-locale: false
  mail:
    host: ${SMTP_HOST}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    port: ${SMTP_PORT}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
pagination:
  post:
    blog: 5
  comments: 5
  items-per-page: 10
